COPY INTO RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES
FROM @%TAXI_DRIVE_SMALL_FILES
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null') EMPTY_FIELD_AS_NULL=TRUE)
ON_ERROR = 'CONTINUE';

select * from RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES;

LIST @%TAXI_DRIVE_SMALL_FILES;

PUT 'file:///C:/Users/user/Desktop/DE/Projects/DataWar/1_SnowFlake/5_Data/archive/train.csv' @%TAXI_DRIVE_SMALL_FILES;

COPY INTO RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES
FROM @%TAXI_DRIVE_SMALL_FILES
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null') EMPTY_FIELD_AS_NULL=TRUE)
ON_ERROR = 'CONTINUE';

COPY INTO RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES
FROM (
  SELECT t.$1,
         t.$2,
         IFF(t.$3 = '', NULL, t.$3),   -- empty ORIGIN_CALL -> NULL
         IFF(t.$4 = '', NULL, t.$4),   -- empty ORIGIN_STAND -> NULL
         t.$5, t.$6, t.$7, t.$8, t.$9
  FROM '@RAHUL_DB.PUBLIC.%TAXI_DRIVE_SMALL_FILES' t
)
FILE_FORMAT = (
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('')
)
ON_ERROR = 'CONTINUE';

select count(*) from RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES;

SELECT count(*) AS TOTAL_ROWS,
       count(DISTINCT TRIP_ID) AS DISTINCT_TRIPS
FROM RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES;