COPY INTO RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES
FROM @%TAXI_DRIVE_SMALL_FILES
FILE_FORMAT = (TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('','NULL','null') EMPTY_FIELD_AS_NULL=TRUE)
ON_ERROR = 'CONTINUE';

select * from RAHUL_DB.PUBLIC.TAXI_DRIVE_SMALL_FILES;

LIST @%TAXI_DRIVE_SMALL_FILES;